name: Lichess Bot Runner

on:
  push:
    branches: [ master, main ]
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Stockfish 19 Engine
      run: |
        mkdir -p engines
        # Завантажуємо архів за прямим посиланням
        wget https://github.com
        # Розпаковуємо його
        tar -xvf stockfish-19-ubuntu-x86-64.tar
        # Переносимо у потрібну папку
        mv stockfish-19/stockfish-19-ubuntu-x86-64 engines/stockfish
        chmod +x engines/stockfish
        # Видаляємо сміття
        rm -rf stockfish-19 stockfish-19-ubuntu-x86-64.tar
